# Source: https://github.com/docker-library/docs/tree/master/nextcloud
networks:
  nextcloud:
  nextcloud-proxy:
    name: nextcloud-proxy

secrets:
  nextcloud_db_root_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/nextcloud_db_root_password
  nextcloud_db_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/nextcloud_db_password
  server_admin_username:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/server_admin_username
  server_admin_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/server_admin_password

services:
  traefik:
    networks:
      - nextcloud-proxy

  nextcloud-db:
    container_name: nextcloud_db
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 1m
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nextcloud
    secrets:
      - nextcloud_db_root_password
      - nextcloud_db_password
    volumes:
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/nextcloud_db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_MYSQL_LOCALHOST_USER=1

  nextcloud-app:
    container_name: nextcloud_app
    image: nextcloud:${NEXTCLOUD_VERSION:-production}
    restart: always
    depends_on:
      nextcloud-db:
        condition: service_healthy
    networks:
      - nextcloud
      - nextcloud-proxy
    secrets:  
      - nextcloud_db_password
      - server_admin_username
      - server_admin_password
      - oidc_nextcloud_password
    volumes:
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/app:/var/www/html
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/hooks/post-installation:/docker-entrypoint-hooks.d/post-installation
      - ${NEXTCLOUD_DATA_LOCATION:-/usr/local/nextcloud}:/var/www/html/data
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/server_admin_username
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/server_admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}
      - SMTP_HOST=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_NAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${SMTP_SENDER}
      - MAIL_DOMAIN=${CF_DOMAIN_NAME}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
      - CF_DOMAIN_NAME=${CF_DOMAIN_NAME}
      - OIDC_NEXTCLOUD_CLIENT_ID=${OIDC_NEXTCLOUD_CLIENT_ID}
    labels:
      dns.manage: true
      dns.cloudflare.proxied: true
      traefik.enable: true
      traefik.docker.network: nextcloud-proxy
      traefik.http.routers.nextcloud-server.entryPoints: cloudflare
      traefik.http.routers.nextcloud-server.rule: Host(`${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}`)
      traefik.http.services.nextcloud-server.loadbalancer.server.port: 80