# Source: https://github.com/docker-library/docs/tree/master/nextcloud
networks:
  nextcloud:
  nextcloud-proxy:
    name: nextcloud-proxy

secrets:
  nextcloud_db_root_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/nextcloud_db_root_password
  nextcloud_db_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/nextcloud_db_password
  server_admin_username:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/server_admin_username
  server_admin_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/server_admin_password
  nextcloud_elastic_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/nextcloud_elastic_password
  elastic_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/elastic_password
  oidc_nextcloud_digest:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/oidc_nextcloud_digest
  oidc_nextcloud_password:
    file: ${APPDATA_LOCATION:-/srv/appdata}/secrets/oidc_nextcloud_password

services:
  traefik:
    networks:
      nextcloud-proxy:
        aliases:
          - ${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}
          - ${COLLABORA_SUBDOMAIN:-office}.${CF_DOMAIN_NAME}

  authelia:
    secrets:
      - oidc_nextcloud_digest
    environment:
      OIDC_NEXTCLOUD_CLIENT_ID: ${OIDC_NEXTCLOUD_CLIENT_ID}

  nextcloud-db:
    container_name: nextcloud_db
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 5m
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nextcloud
    secrets:
      - nextcloud_db_root_password
      - nextcloud_db_password
    volumes:
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/nextcloud_db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_MYSQL_LOCALHOST_USER=1

  nextcloud-app:
    container_name: nextcloud_app
    image: nextcloud:${NEXTCLOUD_VERSION:-production}
    restart: always
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-elastic:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "/health/check.sh"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10m
      start_interval: 5s
    networks:
      - nextcloud
      - nextcloud-proxy
    secrets:  
      - nextcloud_db_password
      - server_admin_username
      - server_admin_password
      - oidc_nextcloud_password
      - nextcloud_elastic_password
    volumes:
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/app:/var/www/html
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/health:/health
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/hooks/post-installation:/docker-entrypoint-hooks.d/post-installation
      - ${NEXTCLOUD_DATA_LOCATION:-/usr/local/nextcloud}:/var/www/html/data
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_DEFAULT_QUOTA=${NEXTCLOUD_DEFAULT_QUOTA}
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/server_admin_username
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/server_admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}
      - SMTP_HOST=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_NAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${SMTP_SENDER}
      - MAIL_DOMAIN=${CF_DOMAIN_NAME}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
      - CF_DOMAIN_NAME=${CF_DOMAIN_NAME}
      - COLLABORA_SERVER_NAME=${COLLABORA_SUBDOMAIN:-office}.${CF_DOMAIN_NAME}
      - OIDC_NEXTCLOUD_CLIENT_ID=${OIDC_NEXTCLOUD_CLIENT_ID}
      - ELASTIC_SEARCH_HOST=nextcloud-elastic
      - ELASTIC_SEARCH_INDEX=elastic
      - ELASTIC_SEARCH_USER=elastic
      - ELASTIC_SEARCH_PASSWORD_FILE=/run/secrets/nextcloud_elastic_password
    labels:
      dns.manage: true
      dns.cloudflare.proxied: true
      traefik.enable: true
      traefik.docker.network: nextcloud-proxy
      traefik.http.routers.nextcloud-server.entryPoints: cloudflare,tailnet
      traefik.http.routers.nextcloud-server.rule: Host(`${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}`)
      traefik.http.services.nextcloud-server.loadbalancer.server.port: 80

  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    networks:
      - nextcloud-proxy
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:9980/"]
      start_period: 1m
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      TZ: ${TZ}
      aliasgroup1: https://${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${CF_DOMAIN_NAME}
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:admin_console.enable=false"
    labels:
      dns.manage: true
      dns.cloudflare.proxied: true
      traefik.enable: true
      traefik.docker.network: nextcloud-proxy
      traefik.http.routers.collabora.entryPoints: cloudflare,tailnet
      traefik.http.routers.collabora.rule: Host(`${COLLABORA_SUBDOMAIN:-office}.${CF_DOMAIN_NAME}`)
      traefik.http.services.collabora.loadbalancer.server.port: 9980

  nextcloud-elastic:
    container_name: nextcloud_elastic
    image: elasticsearch:8.16.2
    restart: always
    healthcheck:
      # If properly secured, the ES API should return 401 once fully initialized
      test: ["CMD-SHELL", "status_code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:9200 -k) && [ \"$$status_code\" = \"401\" ]"]
      start_period: 5m
      interval: 10s
      timeout: 5s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: ${NEXTCLOUD_FTS_MEMORY_LIMIT}
    secrets:
      - elastic_password
    networks:
      - nextcloud
    volumes:
      - ${APPDATA_LOCATION:-/srv/appdata}/nextcloud/search:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true                  # Disable use of swap
      - discovery.type=single-node                  # Disable warnings about single-node cluster
      - xpack.security.enabled=true                 # Enable security
      - xpack.security.authc.api_key.enabled=true   # Enable API Key authentication
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_password